Initial implementation for `DssLitePsm`
makerdao/dss-lite-psm pull request #1
Opened 2023-10-04 14:35 UTC by amusingaxl

2023-10-13 12:31 UTC, DaiFoundation-DevOps commented
[![CLA assistant check](https://cla.daifoundation.org/pull/badge/not_signed)](https://cla.daifoundation.org/makerdao/dss-lite-psm?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.daifoundation.org/makerdao/dss-lite-psm?pullRequest=1) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: sunbreak1211<br/>:x: amusingaxl<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.daifoundation.org/check/makerdao/dss-lite-psm?pullRequest=1) it.</sub>

2023-10-13 14:09 UTC, sunbreak1211 commented on .github/workflows/test.yml
> +      - master
> And what do you do after it's fully audited and deployed?

We merge it to `master`.

2023-10-13 14:37 UTC, 0xcentur1on submitted a review, later dismissed
LGTM!

2023-10-16 17:44 UTC, oldchili commented on src/DssKeg.sol
> +    address public immutable mgr;
As an approval function was indeed added I'm resolving

2023-10-17 10:11 UTC, 0xdecr1pto submitted a review, later dismissed
LGTM…. No issues was found

2023-10-17 15:38 UTC, 0xp3th1um submitted a review, later dismissed
Good job!

2023-10-18 13:47 UTC, oldchili requested changes
Note that the tests were just glanced at.
There is mainly a comment about removing the usage of `vat.Line` in gush().
Also an improvement suggestion for `fill` and `trim`.
Other than that more minor comments.

2023-10-18 13:47 UTC, oldchili commented on src/DssLitePsm.sol
> +            require(data <= WAD, "DssLitePsm/out-of-range");
```suggestion
            require(data <= WAD, "DssLitePsm/tin-out-of-range");
```
Just a suggestion since we now have the error message twice.

2023-10-18 13:47 UTC, oldchili commented on src/DssLitePsm.sol
> +            require(data <= WAD, "DssLitePsm/out-of-range");
```suggestion
            require(data <= WAD, "DssLitePsm/tout-out-of-range");
```
again, just a suggestion.

2023-10-18 13:47 UTC, oldchili commented on src/DssLitePsm.sol
> +    function _sellGem(address usr, uint256 gemAmt, uint256 tin_) internal returns (uint256 daiOutWad) {
Not sure, but do we need the elaborated natspec for internal functions?.
If we keep it, might be worth mentioning it's an internal function in the @notice.

2023-10-18 13:47 UTC, oldchili commented on src/DssLitePsm.sol
> +    function _buyGem(address usr, uint256 gemAmt, uint256 tout_) internal returns (uint256 daiInWad) {
same here about the natspec.

2023-10-18 13:47 UTC, oldchili commented on src/DssLitePsm.sol
> +        vat.slip(ilk, address(this), swad);
So, there is a potential gas improvement here.
We do not actually need to be `slip`ping and `frob`bing the `ink` all the time.

We could follow an approach as `AllocatorVault` and just let the deployment init script set an initial high number. Something like it allows to mint up to 10B or so.

Then you can:
-remove completely the `slip` call per `fill` and `trim`
-make `frob` cheaper, passing `address(0)` on `v` and also 0 amount on `dink`.
-avoid the need for the `swad` variable.
-this also removes the need of having to `rely` the PSM in the `Vat`.

The potential annoyance on this approach is related to ES, but if it is not longer supported than it shouldn't matter.

If you think it is worth it we can send a PR for it, or you can do it yourself.

2023-10-18 13:47 UTC, oldchili commented on src/DssLitePsm.sol
> +        require(vow != address(0), "DssLitePsm/chug-missing-vow");
Not sure why you have reverted the `address vow_ = vow;` caching, but should be back.

2023-10-18 13:47 UTC, oldchili commented on src/DssLitePsm.sol
> +                _divup(_subcap(vat.debt(), vat.Line()), RAY)
We gave it some thought and think the unwinding due to `vat.Line` should be removed.

There's no obvious reason that a PSM should seek to unwind itself due only to the global debt ceiling being exceeded. It essentially takes some flexibility away from governance, making all PSMs attempt to unwind when `vat.debt()` > `vat.Line()`. There could be cases where that is not desired, or only certain PSMs should unwind. Governance can control per-PSM parameters to unwind any given PSM, so it's not like functionality is lost by removing this.

Also there are some problematic edge cases with the current code if for example `vat.Line()` is 0, then the frob might fail since the dai balance might be more than the debt (because of fees). It could be solved with more conditions but probably not worth it.

2023-10-18 13:47 UTC, oldchili commented on src/DssPocket.sol
> +    function approve(address spender, uint256 value) external;
```suggestion
    function approve(address, uint256) external;
```
To be consistent with other places.

2023-10-18 13:47 UTC, oldchili commented on src/DssPocket.sol
> +
```suggestion
```
nit - usually setting the wards and the `emit Rely` lines are right after the other.

2023-10-18 13:47 UTC, oldchili commented on src/DssPocket.sol
> +    function hope(address who) public auth {
```suggestion
    function hope(address who) external auth {
```

2023-10-18 13:47 UTC, oldchili commented on src/DssPocket.sol
> +    function nope(address who) public auth {
```suggestion
    function nope(address who) external auth {
```

2023-10-18 13:47 UTC, oldchili commented on src/DssPocket.sol
> +    function hope(address who) public auth {
also consider changing `who` to `usr` here as well.

2023-10-18 13:47 UTC, oldchili commented on src/DssPocket.sol
> +    function nope(address who) public auth {
also consider changing `who` to `usr` here as well.

2023-10-18 13:47 UTC, oldchili commented on src/DssLitePsm.integration.t.sol
> +    function transfer(address to, uint256 value) external returns (bool);
```suggestion
    function transfer(address to, uint256 value) external;
```

2023-10-18 13:47 UTC, oldchili commented on src/DssLitePsm.integration.t.sol
> +    function transferFrom(address from, address to, uint256 value) external returns (bool);
```suggestion
```

2023-10-18 13:47 UTC, oldchili commented on src/DssLitePsm.integration.t.sol
> +    function ilks(bytes32) external view returns (uint256 line, uint256 gap, uint48 ttl, uint48 last, uint48 lastInc);
```suggestion
```

2023-10-18 13:47 UTC, oldchili commented on src/DssLitePsm.integration.t.sol
> +    address immutable chainlog = vm.envAddress("CHANGELOG");
Why do we need to define a "CHANGELOG" env var? can't we just hard-code it?

2023-10-18 13:47 UTC, oldchili commented on src/DssLitePsm.integration.t.sol
> +        // Mints 100_000_000 USDC into the test contract.
```suggestion
        // Mints 100_000_000 gem into the test contract.
```

2023-10-18 13:47 UTC, oldchili commented on src/DssLitePsm.integration.t.sol
> +        // pocket to give unlimited USDC approval to the litePsm.
```suggestion
        // pocket to give unlimited gem approval to the litePsm.
```

2023-10-18 13:47 UTC, oldchili commented on src/DssLitePsm.integration.t.sol
> +    function testOnlyBudMethods() public {
```suggestion
    function testTollMethods() public {
```

2023-10-18 13:47 UTC, oldchili commented on src/DssLitePsm.integration.t.sol
> +        uint256 pusdcBalancePocket = gem.balanceOf(address(pocket));
In theory, we should change here and in every test of this abstract contract the `usdc` keyword to `gem`

2023-10-18 13:47 UTC, oldchili commented on src/DssLitePsm.integration.t.sol
> +        );
```suggestion
        assertEq(litePsm.cut(), 0, "chug: invalid cut after chug");
```

2023-10-18 14:51 UTC, amusingaxl commented on src/DssLitePsm.sol
> +        unchecked {
Is this the expected behavior, though? Shouldn't we revert if `y = 0`?

2023-10-18 15:24 UTC, amusingaxl commented on src/DssLitePsm.sol
> +        vat.slip(ilk, address(this), swad);
I got the general idea, however this would create an unwanted external dependency.
If we set it to 10B, we need to keep in mind that the contract would stop working if the debt ceiling is ever set to a value larger than that.

It's yet another thing that we will need to keep in the collective brain of those working with MakerDAO.
Honestly, it seems like something that can easily be forgotten and really painful to debug during an emergency spell.

These functions are meant to be called by keepers, so gas costs will be paid primarily by the MakerDAO anyway, so I'm not sure if it's worth the savings.

Even though the chances of running into this issue are pretty slim, I believe this would feel like a [Damocles' Sword](https://en.wikipedia.org/wiki/Damocles)

2023-10-18 15:36 UTC, amusingaxl commented on src/DssLitePsm.sol
> +                _divup(_subcap(vat.debt(), vat.Line()), RAY)
It makes sense... I'll remove this

2023-10-18 15:39 UTC, sunbreak1211 commented on src/DssLitePsm.sol
> +        require(vow != address(0), "DssLitePsm/chug-missing-vow");
Yeah fair, just wondering that it is a pretty simple optimization to not do it.

2023-10-18 15:40 UTC, amusingaxl commented on src/DssLitePsm.integration.t.sol
> +    address immutable chainlog = vm.envAddress("CHANGELOG");
I guess there's no harm in hard-coding this one.

2023-10-18 16:11 UTC, amusingaxl commented on README.md
> +`DssLitePsm` completely disregards Emergency Shutdown. This is intentional, as it complicates a lot the design.
Done

2023-10-18 16:18 UTC, amusingaxl commented on README.md
>  TODO.
Added the relevant section.

2023-10-18 16:57 UTC, amusingaxl commented on src/DssLitePsm.integration.t.sol
> +        // Mints 100_000_000 USDC into the test contract.
Fixed

2023-10-18 16:59 UTC, amusingaxl commented on src/DssLitePsm.integration.t.sol
> +        );
Fixed

2023-10-18 17:03 UTC, amusingaxl commented on src/DssLitePsm.sol
> +        require(vow != address(0), "DssLitePsm/chug-missing-vow");
Before caching `vow`:

| src/DssLitePsm.integration.t.sol:Harness__DssLitePsm contract |                 |        |        |        |         |
|---------------------------------------------------------------|-----------------|--------|--------|--------|---------|
| Deployment Cost                                               | Deployment Size |        |        |        |         |
| 1682486                                                       | 9713            |        |        |        |         |
| Function Name                                                 | min             | avg    | median | max    | # calls |
| chug                                                          | 30498           | 30498  | 30498  | 30498  | 1       |

After caching `vow`:

| src/DssLitePsm.integration.t.sol:Harness__DssLitePsm contract |                 |        |        |        |         |
|---------------------------------------------------------------|-----------------|--------|--------|--------|---------|
| Deployment Cost                                               | Deployment Size |        |        |        |         |
| 1679479                                                       | 9698            |        |        |        |         |
| Function Name                                                 | min             | avg    | median | max    | # calls |
| chug                                                          | 30394           | 30394  | 30394  | 30394  | 1       |

The actual gas saving with optimizations enabled is 104 gas. We also gain some 3007 gas when deploying the contract.

I'll add this change, since it's quite simple, as you said yourself.

2023-10-18 17:15 UTC, amusingaxl commented on src/DssLitePsm.sol
> +    event Kiss(address indexed who);
Done

2023-10-18 17:15 UTC, amusingaxl commented on src/DssLitePsm.sol
> +        require(bud[msg.sender] == 1, "DssLitePsm/not-bud");
Done

2023-10-18 17:18 UTC, amusingaxl commented on src/DssLitePsm.sol
> +        unchecked {
I'd say the function should be formally correct, regardless of usage pattern in this specific implementation.

However since we agreed on removing the unwinding due to global debt ceiling, this function is no longer needed.

2023-10-18 17:18 UTC, amusingaxl commented on src/DssLitePsm.sol
> +    function kiss(address who) public auth {
Done

2023-10-18 17:18 UTC, amusingaxl commented on src/DssLitePsm.sol
> +    function diss(address who) public auth {
Done

2023-10-18 17:33 UTC, amusingaxl commented on src/DssLitePsm.sol
> +    function file(bytes32 what, uint256 data) external auth {
Aren't fees denominated in Dai?
First thing we do when calculating the fee is converting `gemAmt` to `wad` precision, so I don't think this applies.

I created a small test case to demonstrate that you can set fees lower than `10**gem.decimals()` and still they would be applicable:

```solidity
    function testFeeTooLow() public {
        uint256 base = 10 ** gem.decimals();
        // Set fees lower than gem decimals
        litePsm.file("tin", base / 100);
        litePsm.file("tout", base / 100);

        litePsm.fill();
        // Sell 0.01 gem
        uint256 daiOutWad = litePsm.sellGem(address(this), _wadToAmt(1 * WAD) / 100);

        // Fees would still apply
        assertLe(daiOutWad, 1 * WAD / 100);
    }
```

2023-10-18 17:42 UTC, amusingaxl commented on src/DssLitePsm.sol
> +    function file(bytes32 what, uint256 data) external auth {
Okay, I think I got what you mean:

```solidity
    function testFeeTooLow() public {
        uint256 base = 10 ** gem.decimals();
        // Set fees lower than gem decimals
        litePsm.file("tin", 999_999 * base / 1_000_000);
        litePsm.file("tout", 999_999 * base / 1_000_000);

        litePsm.fill();
        // Sell 1 fractional unit of gem
        uint256 daiOutWad = litePsm.sellGem(address(this), 1);

        // Fees would still apply
        assertLt(daiOutWad, 10**(18 - gem.decimals())); // WILL FAIL!
    }
```

2023-10-18 17:45 UTC, amusingaxl commented on src/DssLitePsm.sol
> +    function file(bytes32 what, uint256 data) external auth {
However, in case gem has 18 decimals, we can no longer use that condition `tin >= 10**gem.decimals()`, as it would mean fees cannot be lower than 100%.

2023-10-18 17:45 UTC, amusingaxl commented on src/DssLitePsm.sol
> +            require(data <= WAD, "DssLitePsm/out-of-range");
Done

2023-10-18 17:46 UTC, amusingaxl commented on src/DssLitePsm.sol
> +            require(data <= WAD, "DssLitePsm/out-of-range");
Done

2023-10-18 19:51 UTC, amusingaxl commented on README.md
> +**pool** of pre-minted Dai and stablecoins, reducing the base case of a swap to 2 ERC-20 token transfers with little
Done

2023-10-18 19:52 UTC, amusingaxl commented on src/DssLitePsm.sol
> +    /// @dev This contract should be able freely transfer `gem` on behalf of `pocket`.
Done

2023-10-18 19:54 UTC, amusingaxl commented on src/DssPocket.sol
> +    function approve(address spender, uint256 value) external;
Done

2023-10-18 19:54 UTC, amusingaxl commented on src/DssPocket.sol
> +    function hope(address who) public auth {
Done

2023-10-18 19:54 UTC, amusingaxl commented on src/DssPocket.sol
> +    function nope(address who) public auth {
Done

2023-10-18 19:54 UTC, amusingaxl commented on src/DssLitePsm.integration.t.sol
> +    function transfer(address to, uint256 value) external returns (bool);
Done

2023-10-18 19:54 UTC, amusingaxl commented on src/DssLitePsm.integration.t.sol
> +    function transferFrom(address from, address to, uint256 value) external returns (bool);
Done

2023-10-18 19:54 UTC, amusingaxl commented on src/DssLitePsm.integration.t.sol
> +    function ilks(bytes32) external view returns (uint256 line, uint256 gap, uint48 ttl, uint48 last, uint48 lastInc);
Done

2023-10-18 19:55 UTC, amusingaxl commented on src/DssLitePsm.integration.t.sol
> +        // pocket to give unlimited USDC approval to the litePsm.
Done

2023-10-18 19:55 UTC, amusingaxl commented on src/DssLitePsm.integration.t.sol
> +    function testOnlyBudMethods() public {
Done

2023-10-18 19:55 UTC, amusingaxl commented on src/DssLitePsm.integration.t.sol
> +        uint256 pusdcBalancePocket = gem.balanceOf(address(pocket));
Done

2023-10-18 19:59 UTC, amusingaxl commented on src/DssLitePsm.sol
> +    function _sellGem(address usr, uint256 gemAmt, uint256 tin_) internal returns (uint256 daiOutWad) {
I rather keep them. Changed the `@notice` description to make it explicit.

2023-10-18 19:59 UTC, amusingaxl commented on src/DssLitePsm.sol
> +    function _buyGem(address usr, uint256 gemAmt, uint256 tout_) internal returns (uint256 daiInWad) {
I rather keep them. Changed the `@notice` description to make it explicit.

2023-10-18 20:49 UTC, sunbreak1211 commented on README.md
> +**pool** of pre-minted Dai and stablecoins, reducing the base case of a swap to 2 ERC-20 token transfers with little
LGTM

2023-10-18 20:50 UTC, sunbreak1211 commented on README.md
> +proposal do increase the swapping fees `tin` and `tout`. That is done through an Executive Spell, which is an on-chain
```suggestion
proposal to increase the swapping fees `tin` and/or `tout`. That is done through an Executive Spell, which is an on-chain
```

2023-10-18 20:51 UTC, sunbreak1211 commented on README.md
> +
LGTM excepting a minor modification in a line.

2023-10-18 20:52 UTC, sunbreak1211 commented on README.md
> +
```suggestion
```

2023-10-18 20:52 UTC, sunbreak1211 commented on README.md
> +
LGTM

2023-10-18 20:53 UTC, sunbreak1211 commented on README.md
> +`DssLitePsm` completely disregards Emergency Shutdown. This is intentional, as it complicates a lot the design.
LGTM

2023-10-18 20:55 UTC, sunbreak1211 commented on README.md
>  TODO.
LGTM

2023-10-18 21:16 UTC, telome commented on src/DssLitePsm.sol
> +    function file(bytes32 what, uint256 data) external auth {
Note that the math below is incorrect (you'd need the RHS of the inequality to be 1 and not 0 for your derivation to hold).

> To have fee > 0, we need:
> 
> ```
> gemAmt * to18ConversionFactor * tin / WAD > 0
> 
> tin > WAD / (gemAmt * to18ConversionFactor)


It's probably fine to document the limitation one way or another, so either by mentioning something like "we assume that `decimals << 18` and that `tin` and `tout` will be set to either 0 or some value greater than `10**decimals` so that all swaps correctly apply fees", or alternatively something like "we accept the limitation that fees may not apply due to rounding errors for small swaps where `gemAmt < 10**decimals / tin`.

2023-10-18 21:44 UTC, amusingaxl commented
Enabling `solc` optimizer will reduce the overall gas cost for deploying and using `DssLitePsm` as follows:

`optimizer = false`:

| Deployment Cost         | Deployment Size   |         |            |          |             |
| ----------------------  | ----------------: | ------: | -------:   | -------: | --------:   |
| 2563988                 | 15030             |         |            |          |             |
| ----------------------  | ----------------- | ------- | --------   | -------- | ---------   |
| **Function Name**       | **min**           | **avg** | **median** | **max**  | **# calls** |
| ----------------------  | ----------------- | ------- | --------   | -------- | ---------   |
| `buf`                   | 520               | 920     | 520        | 2520     | 5           |
| `buyGem`                | 9010              | 34009   | 24767      | 67972    | 11          |
| `buyGemNoFee`           | 3197              | 10201   | 10201      | 17206    | 2           |
| `chug`                  | 708               | 24866   | 28204      | 34453    | 10          |
| `cut`                   | 6094              | 6100    | 6104       | 6104     | 9           |
| `deny`                  | 999               | 2873    | 3902       | 3902     | 5           |
| `diss`                  | 1044              | 1044    | 1044       | 1044     | 1           |
| `file(bytes32,address)` | 1214              | 21498   | 24748      | 24748    | 33          |
| `file(bytes32,uint256)` | 1122              | 18809   | 24602      | 26580    | 63          |
| `fill`                  | 8130              | 94153   | 63219      | 171818   | 46          |
| `gem`                   | 623               | 623     | 623        | 623      | 1           |
| `kiss`                  | 1020              | 12559   | 12559      | 24098    | 2           |
| `pocket`                | 445               | 445     | 445        | 445      | 5           |
| `rely`                  | 999               | 11488   | 11488      | 21977    | 2           |
| `sellGem`               | 9141              | 36252   | 46722      | 75502    | 32          |
| `sellGemNoFee`          | 3217              | 27876   | 27876      | 52535    | 2           |
| `tin`                   | 475               | 1475    | 1475       | 2475     | 2           |
| `tout`                  | 539               | 1539    | 1539       | 2539     | 2           |
| `trim`                  | 7404              | 30945   | 47003      | 50195    | 7           |
| `vow`                   | 582               | 1582    | 1582       | 2582     | 2           |
| `wards`                 | 881               | 1325    | 881        | 2881     | 18          |


---


`optimizer = true`

| DssLitePsm              |                   |         |            |          |             |
| ----------------------  | ----------------: | ------: | -------:   | -------: | --------:   |
| Deployment Cost         | Deployment Size   |         |            |          |             |
| 1622756                 | 9387              |         |            |          |             |
| ----------------------  | ----------------- | ------- | --------   | -------- | ---------   |
| **Function Name**       | **min**           | **avg** | **median** | **max**  | **# calls** |
| ----------------------  | ----------------- | ------- | --------   | -------- | ---------   |
| `buf`                   | 375               | 775     | 375        | 2375     | 5           |
| `buyGem`                | 7814              | 34525   | 22880      | 66440    | 11          |
| `buyGemNoFee`           | 2682              | 9323    | 9323       | 15964    | 2           |
| `chug`                  | 485               | 23137   | 26351      | 32394    | 10          |
| `cut`                   | 4445              | 4451    | 4455       | 4455     | 9           |
| `deny`                  | 669               | 2682    | 3746       | 3746     | 5           |
| `diss`                  | 714               | 714     | 714        | 714      | 1           |
| `file(bytes32,address)` | 739               | 21021   | 24265      | 24265    | 33          |
| `file(bytes32,uint256)` | 612               | 18353   | 24145      | 26113    | 63          |
| `fill`                  | 5965              | 91230   | 60396      | 168289   | 46          |
| `gem`                   | 283               | 283     | 283        | 283      | 1           |
| `kiss`                  | 690               | 12299   | 12299      | 23909    | 2           |
| `pocket`                | 283               | 283     | 283        | 283      | 5           |
| `rely`                  | 669               | 11225   | 11225      | 21782    | 2           |
| `sellGem`               | 8079              | 34453   | 45612      | 74115    | 32          |
| `sellGemNoFee`          | 2713              | 26920   | 26920      | 51127    | 2           |
| `tin`                   | 330               | 1330    | 1330       | 2330     | 2           |
| `tout`                  | 394               | 1394    | 1394       | 2394     | 2           |
| `trim`                  | 5346              | 28472   | 44220      | 47412    | 7           |
| `vow`                   | 405               | 1405    | 1405       | 2405     | 2           |
| `wards`                 | 578               | 1022    | 578        | 2578     | 18          |


---

Difference:


| Deployment Cost         | Deployment Size   |           |          |           |            |              |          |           |
| ----------------------  | ----------------- | ------:   | -------: | -------:  | ------:    | -------:     | -------: | --------: |
| -943232 (-36.75%)       | -5653 (-37.85%)   |           |          |           |            |              |          |           |
| **Function Name**       | **min**           | **% min** | **avg**  | **% avg** | **median** | **% median** | **max**  | **% max** |
| ----------------------  | ----------------- | -------   | -------- | --------  | -------    | --------     | -------- | --------  |
| `buf`                   | -145              | -27.88%   | -145     | -15.81%   | -145       | -28.08%      | -145     | -37.80%   |
| `buyGem`                | -1196             | -13.26%   | 524      | 1.54%     | -1897      | -7.54%       | -1544    | -2.29%    |
| `buyGemNoFee`           | -515              | -16.09%   | -885     | -8.68%    | -885       | -8.68%       | -1242    | -7.22%    |
| `chug`                  | -223              | -24.00%   | -1745    | -7.00%    | -18453     | -66.00%      | -2060    | -5.98%    |
| `cut`                   | -1649             | -27.03%   | -1650    | -27.00%   | -1649      | -27.03%      | -1649    | -27.00%   |
| `deny`                  | -330              | -33.03%   | -191     | -6.63%    | -156       | -3.99%       | -156     | -3.99%    |
| `diss`                  | -330              | -31.65%   | -330     | -31.65%   | -330       | -31.65%      | -330     | -31.65%   |
| `file(bytes32,address)` | -475              | -39.11%   | -482     | -2.25%    | -483       | -1.95%       | -483     | -1.95%    |
| `file(bytes32,uint256)` | -510              | -45.54%   | -456     | -2.43%    | -457       | -1.85%       | -467     | -1.76%    |
| `fill`                  | -2165             | -23.18%   | -2936    | -3.24%    | -2823      | -4.61%       | -5529    | -3.22%    |
| `gem`                   | -340              | -54.67%   | -340     | -54.67%   | -340       | -54.67%      | -340     | -54.67%   |
| `kiss`                  | -330              | -32.35%   | -260     | -2.06%    | -260       | -2.06%       | -189     | -0.78%    |
| `pocket`                | -162              | -36.18%   | -162     | -36.18%   | -162       | -36.18%      | -162     | -36.18%   |
| `rely`                  | -330              | -33.03%   | -263     | -18.61%   | -263       | -18.61%      | -195     | -11.25 [...]

2023-10-18 21:50 UTC, sunbreak1211 commented on src/DssLitePsm.sol
> +    event Kiss(address indexed who);
LGTM

2023-10-18 21:52 UTC, sunbreak1211 commented on src/DssLitePsm.sol
> +        unchecked {
> I'd say the function should be formally correct, regardless of usage pattern in this specific implementation.
> 
> However since we agreed on removing the unwinding due to global debt ceiling, this function is no longer needed.

Yeah I agree, in the case of Allocator we preferred to leave as it is to not have to decide what is the best way to fix this function (which has already been used in other places in this way) as the case didn't apply anyway.
But yeah, good we could remove it now.

2023-10-18 22:04 UTC, amusingaxl commented on src/DssLitePsm.sol
> +    function file(bytes32 what, uint256 data) external auth {
Done.

2023-10-18 22:09 UTC, sunbreak1211 commented on src/DssLitePsm.sol
> +                _divup(_subcap(vat.debt(), vat.Line()), RAY)
LGTM

2023-10-18 22:11 UTC, sunbreak1211 commented on src/DssLitePsm.sol
> +        require(vow != address(0), "DssLitePsm/chug-missing-vow");
LGTM. Great it is changed, wondering why 3007 gas saving on deploying.

2023-10-18 22:34 UTC, sunbreak1211 commented on README.md
> +
Modification looks good as well.

2023-10-19 07:02 UTC, oldchili commented on README.md
> +**pool** of pre-minted Dai and stablecoins, reducing the base case of a swap to 2 ERC-20 token transfers with little
LGTM, resolving

2023-10-19 07:03 UTC, oldchili commented on README.md
> +
LGTM, resolving

2023-10-19 07:03 UTC, oldchili commented on README.md
> +
LGTM, resolving

2023-10-19 07:03 UTC, oldchili commented on README.md
> +`DssLitePsm` completely disregards Emergency Shutdown. This is intentional, as it complicates a lot the design.
LGTM, resolving

2023-10-19 07:05 UTC, oldchili commented on src/DssLitePsm.sol
> +        require(vow != address(0), "DssLitePsm/chug-missing-vow");
LGTM, resolving

2023-10-19 07:05 UTC, oldchili commented on src/DssLitePsm.sol
> +                _divup(_subcap(vat.debt(), vat.Line()), RAY)
LGTM, resolving

2023-10-19 07:10 UTC, oldchili commented on src/DssLitePsm.sol
> +        vat.slip(ilk, address(this), swad);
This change LGTM

2023-10-19 08:17 UTC, telome commented on src/DssLitePsm.sol
> +    function file(bytes32 what, uint256 data) external auth {
Comment LGTM, resolving.

2023-10-19 08:32 UTC, telome commented on src/DssLitePsm.sol
> +        vat.slip(ilk, address(this), swad);
LGTM as well

2023-10-19 11:15 UTC, sunbreak1211 commented on src/DssLitePsm.sol
> +        vat.slip(ilk, address(this), swad);
LGTM

2023-10-19 11:19 UTC, oldchili approved these changes
LGTM

2023-10-19 11:34 UTC, sunbreak1211 commented on src/DssPocket.sol
> +
```suggestion
```
We can apply this together with the audit round of changes

2023-10-19 11:34 UTC, sunbreak1211 submitted a review, later dismissed
LGTM

2023-10-19 11:39 UTC, telome submitted a review, later dismissed
LGTM

2023-10-19 17:03 UTC, amusingaxl commented on README.md
> +     │                               │  │  │
`slip` is no longer called after the latest refactor.
```suggestion
                                  │  │  │  │
                                  │  │  │  │
                  frob            │  │  │  │
     ╭────────────────────────────╯  │  │  │
     │                               │  │  │
```

2023-10-19 17:32 UTC, sunbreak1211 commented on README.md
> +     │                               │  │  │
Yeah looks good, let's leave this one as well for the round after audit feedback.

2023-10-19 17:44 UTC, amusingaxl commented on README.md
> +     │                               │  │  │
Yeah, I'm just adding it here so I don't forget.

2023-10-20 14:51 UTC, amusingaxl commented on src/DssPocket.sol
> +
Done.

2023-12-13 14:21 UTC, amusingaxl commented
I'm closing this in favor of #12, which includes all commits from this branch.

2023-12-15 14:09 UTC, oddaf submitted a review, later dismissed
LGTM

2024-03-05 13:25 UTC, 0xdecr1pto approved these changes

2024-07-09 11:16 UTC, oldchili approved these changes
LGTM

2024-07-09 11:35 UTC, sunbreak1211 approved these changes
LGTM

2024-07-11 13:05 UTC, merged