Refactor: split init script in phases
makerdao/dss-lite-psm pull request #17
Opened 2024-05-20 20:29 UTC by amusingaxl

This PR attempts to implement the new init/migration plan described [here](https://docs.google.com/document/d/1BYapT91VuR-y2Z1eoJ2UrZWRUE051HoMiMWT1nrlWgk).

2024-05-23 00:48 UTC, oddaf approved these changes

2024-05-23 07:50 UTC, 0xdecr1pto submitted a review, later dismissed

2024-05-23 11:27 UTC, 0xp3th1um submitted a review, later dismissed
lgtm

2024-06-03 20:28 UTC, oldchili commented on script/dependencies/phase-1/DssLitePsmInit.sol
> +        require(cfg.psmKey != cfg.pocketKey, "DssLitePsmInit/dst-psm-same-key-pocket");
The test migration part is entirely missing.

2024-06-03 20:28 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        require(src.ink == src.art, "DssLitePsmMigrationPhase2/src-ink-art-mismatch");
This can be manipulated with a vat.dai frob donation, then the spell will revert and become untriggerable (since you can't donate collateral).

2024-06-03 20:28 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        dss.vat.file("Line", dss.vat.Line() + (src.art * RAY));
We are not necessarily moving `src.art` anymore, are we overestimating on purpose?

2024-06-03 20:28 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        uint256 srcGemAmt = ((src.ink - cfg.srcRump) / DssLitePsmLike(dst.psm).to18ConversionFactor());
What happens if `src.ink` is lesser than `cfg.srcRump`? this will revert and the spell will not be able to run.

2024-06-03 20:28 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        require(daiOutWad == src.art - cfg.srcRump, "DssLitePsmMigrationPhase2/invalid-dai-amount");
Because of the rounding down for calculating `srcGemAmt` this will revert if `src.ink - cfg.rump` is not a multiple of the conversion factor.

It can be achieved for example with the same donation manipulation as mentioned above.

2024-06-03 21:01 UTC, amusingaxl commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        dss.vat.file("Line", dss.vat.Line() + (src.art * RAY));
In the end this does not matter, because the value is overwritten by AutoLine in the end of the spell.

2024-06-03 21:02 UTC, amusingaxl commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        require(src.ink == src.art, "DssLitePsmMigrationPhase2/src-ink-art-mismatch");
Probably should go with `<=` then.

2024-06-04 06:59 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        require(src.ink == src.art, "DssLitePsmMigrationPhase2/src-ink-art-mismatch");
Btw just to make sure this case is clear, can see it when adding this code to the beginning of `testLitePsmMigrationPhase2`:

```
deal(address(dss.dai), address(123), 1e13);
vm.prank(address(123)); dss.dai.approve(address(dss.daiJoin), 1e13);
vm.prank(address(123)); dss.daiJoin.join(address(123), 1e13);
vm.prank(address(123)); dss.vat.frob(SRC_ILK, srcPsm, address(0), address(123), int256(0), -int256(1e13));
```

2024-06-04 07:24 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        require(daiOutWad == src.art - cfg.srcRump, "DssLitePsmMigrationPhase2/invalid-dai-amount");
To be a bit more accurate here, it is not (only) a rounding issue per se.

The spell will revert because of a vat.frob donation since `src.ink - cfg.rump` (used for calculating `srcGemAmt`) would be different than `src.art - cfg.rump` (used for the require in line 164).

The rounding-related case where this can fail without a donation is if weird fees are enabled on the PSM anytime before the migration, which would cause `ink` and `art` not to be a multiple of 10**12.
That case is less likely, but still possible.

2024-06-04 07:56 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        require(cfg.dstMaxLine > totalLine, "DssLitePsmMigrationPhase2/max-line-too-low");
Depending on the actual configuration this might still work, but note that even if we use `totalLine` as a temporary over-estimation which would get over-written at the end by the auto-line, checking it against `dstMaxLine` is actually assuming all funds are being migrated.
Maybe the require should check `dstMaxLine` vs `dst.art + srcGemAmt * conversion_factor`?

2024-06-04 08:35 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        dss.vat.file("Line", dss.vat.Line() + (src.art * RAY));
Yeah agree the global Line value is getting recalculated at the end, just not 100% sure its value is exactly what you'd expect anymore.
It is probably ok if we are aware of what we are doing and are overestimating (global Line is not tight anyway), but just wanted to bring attention to this.

2024-06-04 14:30 UTC, amusingaxl commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        require(src.ink == src.art, "DssLitePsmMigrationPhase2/src-ink-art-mismatch");
Actually, are you sure this scenario is possible?
`Vat.frob()` only modifies `art` and `ink` for `u`, not for `v` and `w`.
Even though `gem` for `v` and `dai` for `w` are affected:
https://github.com/makerdao/dss/blob/master/src/vat.sol#L175-L176

2024-06-04 14:40 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        require(src.ink == src.art, "DssLitePsmMigrationPhase2/src-ink-art-mismatch");
When you repay debt, `vat.dai` gets decreased from `w` and `art` gets decreased from `u`.
Check the code above.

2024-06-04 15:02 UTC, amusingaxl commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        require(src.ink == src.art, "DssLitePsmMigrationPhase2/src-ink-art-mismatch");
Got it... I had a stale UI, so I didn't see your comment above before answering.

2024-06-05 17:57 UTC, oddaf submitted a review, later dismissed

2024-06-05 18:22 UTC, 0xdecr1pto approved these changes

2024-06-05 18:48 UTC, oddaf approved these changes

2024-06-05 19:03 UTC, 0xp3th1um submitted a review, later dismissed

2024-06-10 20:06 UTC, oldchili reviewed
We are adding comments on the source files.
Comments for the tests should be uploaded tomorrow.

Main issues:
- Not implementing the requirement to leave X amount of funds in phase 2.
- Tests failing since dstPsm.line is unassigned and still used.
- Temporary line setting for the migration is not calculated correctly, suggest to just use type(uint256).max
- dss.vat.move uses wrong resolution (WAD instead of RAD)
- It's possible to avoid leaving the 100M in the old psm using a flash-loan (we changed our mind a bit here and think it's worth adding a protection, see relevant comment).
	
There are also suggestions for restructuring and cleanups.
	
In order to help us in the process of reviewing this we created a branch with some reference implementation - https://github.com/makerdao/dss-lite-psm/tree/reference-scripts-changes.

We will add links to it to some of the comments, aiming to better explain what we mean.
Feel free to copy parts from there, or if you want just ignore it. Since we were asked not to create a PR that code should not be treated as reviewed/submitted.

2024-06-10 20:18 UTC, amusingaxl commented on script/dependencies/DssLitePsmInit.sol
> +    }
Since dss-allocator is already planned, I see no benefit in changing it here, as it would require updating the code there as well.

2024-06-11 02:01 UTC, sunbreak1211 commented on script/dependencies/DssLitePsmMigration.sol
> +        require(srcPsmKey != dstPsmKey, "DssLitePsmMigration/src-psm-same-key-dst-psm");
Ref: https://github.com/makerdao/dss-lite-psm/blob/reference-scripts-changes/script/dependencies/DssLitePsmMigration.sol#L124

2024-06-11 02:05 UTC, sunbreak1211 commented on script/dependencies/DssLitePsmMigration.sol
> +        require(daiOutWad == mink, "DssLitePsmMigration/invalid-dai-amount");
https://github.com/makerdao/dss-lite-psm/blob/reference-scripts-changes/script/dependencies/DssLitePsmMigration.sol#L131

2024-06-11 02:05 UTC, sunbreak1211 commented on script/dependencies/DssLitePsmMigration.sol
> +        DssLitePsmLike(dst.psm).file("tin", dst.tin);
Also from the structure.

2024-06-11 02:08 UTC, sunbreak1211 commented on script/dependencies/DssLitePsmMigration.sol
> +        (res.src, res.dst) = _getParamsFromKeys(dss, cfg.srcPsmKey, cfg.dstPsmKey);
To give more context to this, removing the usage of the complex structures as return values, we also remove the "need" to call the sub function again, what allows to put everything in just one function and make it more compact and easy to follow.
Also those values that we were refreshing in the second sub function call weren't even be used by the callers, so this seems quite a simplification.

2024-06-11 02:09 UTC, sunbreak1211 commented on script/dependencies/DssLitePsmMigration.sol
> +}
Note that this proposed solution hasn't been implemented in the reference code.

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/DssLitePsmInit.t.integration.sol
>              assertEq(pink, 0, "before: ink is not zero");
Apart from the ink, all the other values here are not checked afterwards, so seems a bit weird to just compare them to 0 here.

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/DssLitePsmInit.t.integration.sol
> +            assertEq(dss.chainlog.getAddress(cfg.pocketKey), pocket, "after: `pocket` not in chainlog");
Since the init scripts are not used in the integration test in the src dir, are we 100% sure that the the module functionality works when using them? (e.g maybe we forgot setting something in the spotter, etc..).

Can't think of anything specific, and also there is some coverage because of the migration selling and filling actions in the migration tests. But still flagging, as we've learned in the past it's good to either incorporate them in the main tests, or test the contracts actions with them separately.

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/DssLitePsmMigration.t.integration.sol
> +        assertGt(psrcInk, 0, "before: src ink is zero");
Apart from maybe the ink, we don't check any of these values later in the test, so a bit weird to just check them in the "before" state. We should check the "After" state as well.

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/DssLitePsmMigration.t.integration.sol
> +        pauseProxy.exec(address(migCaller), abi.encodeCall(migCaller.migrate, (dss, migCfg)));
If possible it might be good to check the migrate function's return values (as this file is more or less a stand-alone test for that function).

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +import {DssLitePsmMigration} from "../DssLitePsmMigration.sol";
unused

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +    function exec(bytes32) external;
unused

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +        migCfg = DssLitePsmMigrationConfigPhase1({
These params don't match the doc.

dstTin,dstTout should be 0
srcMaxLine should be 10B
srcGap should be 350M

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +            dstBuf: 50_000_000 * WAD,
`dstBuf` and `dstGap` will in practice be under 50M.
Suggest to set a lower number (10-20M), so that the limiting factors for minting will be the gap and buff.
Maybe even push to get the real numbers (which are still TBD) and use them.

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +            assertEq(srcInk, psrcInk - migCfg.dstWant, "after: src ink is not decreased by want");
Maybe worth checking src art as well.

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +    }
Might want to check that `line` and `Line` are as expected.

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +    }
Might want to check that the expected amount of dai was filled.

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +    }
Might want to check the balances of the pause-proxy that change in the process are as expected (dai balance, vat.dai balance, vat.gem, maybe vat.sin etc..).

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +    }
I guess also the pocket USDC balance.

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +    }
In case you still prefer keeping the `vat.dai` donation handling it would be good to test it.

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +import {DssLitePsmMigration} from "../DssLitePsmMigration.sol";
unused

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +        mig1Cfg = DssLitePsmMigrationConfigPhase1({
Again, these params don't match the doc.

dstTin,dstTout should be 0
srcMaxLine should be 10B
srcGap should be 350M

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +            srcTout: 0.01 ether,
These should be 0.001 ether (0.1%)

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +        }
The different additional checks that were mentioned in the phase 1 test file are also relevant here.

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +        }
Would be good to test the case where less than 100M exist in the old PSM when we do the 2nd migration.

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +        }
Might also be worth to test in different states of the new psm when the 2nd migration is called (e.g - its line is maximal, it's debt is 0, it's debt is maxed out, etc..).

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +        }
Depending on what is decided to solve the phase 2 flash loan attack issue, that needs to be tested.

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +import {DssLitePsmMigration} from "../DssLitePsmMigration.sol";
unused

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +        mig1Cfg = DssLitePsmMigrationConfigPhase1({
As before:

dstTin,dstTout should be 0
srcMaxLine should be 10B
srcGap should be 350M

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +        mig2Cfg = DssLitePsmMigrationConfigPhase2({
dstTin,dstTout should be 0
srcTin,srcTout should be 0.001 ether
dstWant: wrong

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +            dstTout: 0.03 ether,
dstTin,dstTout should be 0 #

2024-06-11 08:33 UTC, oldchili commented on script/dependencies/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +    }
The different additional checks that were mentioned in phase 1 and 2 tests files are also relevant here.

2024-06-11 15:21 UTC, amusingaxl commented on script/dependencies/DssLitePsmInit.t.integration.sol
>              assertEq(pink, 0, "before: ink is not zero");
These assertions are more of a sanity check that the new PSM has not been initialized yet. If it has, the test will fail either way.
However I should probably make this clear on the assertion messages.

2024-06-11 22:27 UTC, amusingaxl commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.sol
> +// SPDX-FileCopyrightText: © 2023 Dai Foundation <www.daifoundation.org>
> For example if the srcPsm `tin` and `tout` are not 0 after the first migration then the whole analysis changes.
We can add a sanity check for `tin` and `tout` and revert if that's not the case.

Other "dependencies" like this could be locked at the implementation, so we still have the flexibility to set the parameters at the time the spell is being crafted.

If we use hard-coded values, we risk a scenario where the parameters must change due to market conditions, then we have a follow-up audit, only to have the market conditions shifting once again and requiring us to repeat the process.

2024-06-12 00:22 UTC, amusingaxl commented on script/dependencies/DssLitePsmInit.t.integration.sol
> +            assertEq(dss.chainlog.getAddress(cfg.pocketKey), pocket, "after: `pocket` not in chainlog");
I'm changing the integration test at `src/DssLitePsm.t.integration.sol` to use the init scripts.
Notice that the `src/DssLitePsmMom.t.integration.sol` was already using them.

2024-06-12 01:33 UTC, amusingaxl commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +    }
Wouldn't this be a bit redundant?
In practice, we'd be checking whether `AutoLine` executed correctly or not.
We're already asserting that `autoLine.exec()` was called by checking against `last` and `lastInc`.

2024-06-12 02:16 UTC, amusingaxl commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +    }
Removed the donation.

2024-06-12 02:38 UTC, amusingaxl commented on script/dependencies/DssLitePsmMigration.sol
> +}
> * User tries to migrate more and leave the old PSM empty. The old PSM should remain with 100M. That means that in order to succeed with this operation the old PSM should be below 450M funds.

I imagine the flash loan attack would take the form:

```solidity
function attack() external {
    _getLoan();
    spell.cast();
    _repayLoan();
}
```

Let's say there is currently 250M gem in the old PSM.
If we set `dstKeep` to 100M, the way the attacker could circumvent this is:

1. In `_getLoan()`: get 50M gem and sell it for Dai &ndash; Now the old PSM will have 300M gem.
2. The spell is cast and 100M will be kept in the old PSM as per `srcKeep` &ndash; 300M - 100M = 200M will be migrated.
3. In `_repayLoan()`: take the 50M Dai obtained in `_getLoan()` before, swap it for gem using the old PSM and repay the loan &ndash; The result is that now there will be only 50M gems in the old PSM instead of the desired 100M.

If the attack highlighted above is what you meant, how does "check that requires to leave that value in the old PSM" prevent it?
The sanity check will happen in the context of `spell.cast()`, when the amount kept would still be 100M.

Of course, in this case there will be a fee charged in step 3, which would discourage attackers.

Or did you mean that step 3 above should use the new PSM to make the swap and repay? If so, everything cancels out and we still will have the desired 100M in the old PSM.

2024-06-12 02:42 UTC, amusingaxl commented on script/dependencies/DssLitePsmMigration.sol
> +        dss.vat.move(address(this), address(dss.vow), _subcap(daiOutWad, mart));
Removed.

2024-06-12 02:53 UTC, amusingaxl commented on script/dependencies/DssLitePsmInit.sol
> +        require(cfg.psmKey != cfg.pocketKey, "DssLitePsmInit/dst-psm-same-key-pocket");
Done.
See below.

2024-06-12 02:54 UTC, amusingaxl commented on script/dependencies/DssLitePsmMigration.sol
> +interface DssLitePsmLike {
Done.

2024-06-12 02:55 UTC, amusingaxl commented on script/dependencies/DssLitePsmMigration.sol
> +    function _subcap(uint256 x, uint256 y) internal pure returns (uint256 z) {
Still being used.

2024-06-12 02:56 UTC, amusingaxl commented on script/dependencies/DssLitePsmMigration.sol
> +        require(daiOutWad == mink, "DssLitePsmMigration/invalid-dai-amount");
Sanity check to avoid rounding errors was added.

2024-06-12 02:57 UTC, amusingaxl commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +            assertEq(srcInk, psrcInk - migCfg.dstWant, "after: src ink is not decreased by want");
Done. See below.

2024-06-12 02:58 UTC, amusingaxl commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +    }
Done.

2024-06-12 02:59 UTC, amusingaxl commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +    }
I believe all possible related checks are now done.

2024-06-12 02:59 UTC, amusingaxl commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +    }
Done.

2024-06-12 06:56 UTC, oldchili commented on script/dependencies/DssLitePsmMigration.sol
> +}
The scenario we meant is about emptying the gem from the old psm before the spell execution, not about topping it up.

An example:
- Let's say there are 100m gem in the old psm (so exactly the amount that needs to be kept).
- Before the spell executes someone flash loans 100m dai and swaps them in the old psm, so it has no more gem.
- He executes the spell, nothing gets migrated, but fees are turned on for the old psm.
- He sells the 100m gem in the new psm and repays the dai flash loan.

2024-06-12 10:26 UTC, oldchili commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.sol
> +// SPDX-FileCopyrightText: © 2023 Dai Foundation <www.daifoundation.org>
Yeah, guess it is not a mandatory change, but it certainly seemed to have made it more readable.
TBH it can be debate-able if we really need to re-audit for changing a hardcoded value.
But anyway, up to you.

2024-06-12 10:41 UTC, amusingaxl commented on script/dependencies/DssLitePsmMigration.sol
> +}
Couldn't this scenario "flash loan DAI, buy gem in src PSM, sell gem in dst PSM, repay loan" happen at any moment?

The only constraint seems to be the line for dst PSM.

2024-06-12 13:27 UTC, oldchili commented on script/dependencies/DssLitePsmMigration.sol
> +}
In theory it could happen freely after phase 1, and there is not much to do except doing the counter action and rebalancing between the psms if someone deem sit important.
But also as you said, after phase 1 the dst psm line is relatively small, so even if done it is not expected to drain the src psm.

After phase 2 there are fees on the src psm, so it is not possible.
After phase 3 the src psm is already shut down.

2024-06-12 13:59 UTC, amusingaxl commented on script/dependencies/DssLitePsmMigration.sol
> +}
In other words, what exactly prevents this scenario from happening in a transaction placed after the spell cast in the very same block?

2024-06-12 14:19 UTC, amusingaxl commented on script/dependencies/DssLitePsmMigration.sol
> +}
Okay, I think I finally got to the scenario that you meant:

While it's possible to carry out that scenario at any point in time, if the user tries to do it **before** the spell is cast, they will most likely be constrained by the low `line` set for `dstPsm`. If they try to do it **afterwards**, there will be swap fees on `srcPSM`, which would make the costs high enough to disincentivize it.

However, if they do that with a wrapped call to `spell.cast()`, then the cost is actually only the gas spent.

---

If I got that straight, this issue is not completely irreversible. A follow-up spell could send the desired amount back to `srcPsm`. The fees accrued would actually be incorporated into the surplus buffer, which would cancel out in the end.

Still, since putting a spell together is quite time-consuming, `srcPsm` could remain empty for hours or days, breaking integrations that still depend on it.

2024-06-12 14:28 UTC, oldchili commented on script/dependencies/DssLitePsmMigration.sol
> +}
Yes.
Apart from a spell to fix it, there are more counter-strategies listed here:
https://github.com/makerdao/dss-lite-psm/pull/17#discussion_r1633750405

Eventually it seems that putting the require on the src funds is just simplest, but need to be done knowingly while making sure it does not pose other risks (e.g using it in a border-line scenario with regards to the actual PSM funds at the time, while having other mission-critical actions in the same spell).

2024-06-12 20:37 UTC, amusingaxl commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +        }
Done.

2024-06-12 20:42 UTC, amusingaxl commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +        }
Done.

2024-06-12 20:42 UTC, amusingaxl commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +        }
Done.

2024-06-13 13:52 UTC, oldchili commented on script/dependencies/DssLitePsmInit.sol
> +    }
Ok.

2024-06-13 13:57 UTC, oldchili commented on script/dependencies/phase-3/DssLitePsmMigrationPhase3.sol
> +        dss.vat.file(res.src.ilk, "line", 0);
Ok, whatever you prefer.

2024-06-15 00:49 UTC, oddaf requested changes

2024-06-15 00:49 UTC, oddaf commented on src/deployment/DssLitePsmInit.sol
> +pragma solidity ^0.8.16;
```suggestion
pragma solidity 0.8.16;
```
fix compiler version

2024-06-15 00:49 UTC, oddaf commented on src/deployment/DssLitePsmInit.sol
> +}
```suggestion
```
unused

2024-06-15 00:49 UTC, oddaf commented on src/deployment/DssLitePsmInit.sol
> +    function approve(address, uint256) external;
```suggestion
```
unused

2024-06-15 00:49 UTC, oddaf commented on src/deployment/DssLitePsmMigration.sol
> +pragma solidity ^0.8.16;
```suggestion
pragma solidity 0.8.16;
```
fix compiler version

2024-06-15 00:49 UTC, oddaf commented on src/deployment/DssLitePsmMigration.sol
> +    function symbol() external view returns (string memory);
```suggestion
    function approve(address, uint256) external;
```
remove unused functions

2024-06-15 00:49 UTC, oddaf commented on src/deployment/DssLitePsmMigration.sol
> +        uint256 mink = _min(src.ink, move);
Unnecessary, on L152 `move`'s max resulting value is `src.ink` already.

2024-06-15 00:49 UTC, oddaf commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.sol
> +}
```suggestion
```
remove unused interfaces

2024-06-15 00:49 UTC, oddaf commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +import {DssLitePsmInstance} from "../DssLitePsmInstance.sol";
```suggestion
```

unused

2024-06-15 00:49 UTC, oddaf commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +}
```suggestion
```

unused

2024-06-15 00:49 UTC, oddaf commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +    uint256 internal constant RAY = 10 ** 27;
```suggestion
```

unused

2024-06-15 00:49 UTC, oddaf commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.sol
> +import {DssLitePsmInit, DssLitePsmInitConfig} from "../DssLitePsmInit.sol";
```suggestion
```

remove unused imports

2024-06-15 12:58 UTC, amusingaxl commented on src/deployment/DssLitePsmInit.sol
> +pragma solidity ^0.8.16;
In general, we leave the floating pragma in the contracts and fix it in `foundry.toml`.
It makes it easier to reuse code if we need to import it somewhere eles (usually for testing purposes).

2024-06-15 13:02 UTC, amusingaxl commented on src/deployment/DssLitePsmMigration.sol
> +        uint256 mink = _min(src.ink, move);
What do you mean? `src.ink` is the max value, however `move` might be below it.

2024-06-15 13:04 UTC, amusingaxl commented on src/deployment/DssLitePsmMigration.sol
> +pragma solidity ^0.8.16;
Answered above.

2024-06-17 08:57 UTC, oldchili commented on script/dependencies/phase-1/DssLitePsmInit.sol
> +        require(cfg.psmKey != cfg.pocketKey, "DssLitePsmInit/dst-psm-same-key-pocket");
Resolving as there is now a test migration part.

2024-06-17 08:58 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        dss.vat.file("Line", dss.vat.Line() + (src.art * RAY));
resolving, as now type(uint256).max is used.

2024-06-17 08:58 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        uint256 srcGemAmt = ((src.ink - cfg.srcRump) / DssLitePsmLike(dst.psm).to18ConversionFactor());
resolving as this is handled now

2024-06-17 08:59 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        require(daiOutWad == src.art - cfg.srcRump, "DssLitePsmMigrationPhase2/invalid-dai-amount");
Resolving as there is now a check for the rounding.

2024-06-17 09:00 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +        require(cfg.dstMaxLine > totalLine, "DssLitePsmMigrationPhase2/max-line-too-low");
Resolving as this check was removed.

2024-06-17 09:20 UTC, oldchili commented on script/dependencies/DssLitePsmMigration.sol
> +
Resolving as this is now implemented this way.

2024-06-17 09:29 UTC, oldchili commented on script/dependencies/DssLitePsmMigration.sol
> +        dss.vat.heal(mart * RAY);
Resolving as the suggested resolution check was added.

2024-06-17 09:40 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +import {DssLitePsmInstance} from "../DssLitePsmInstance.sol";
Resolving as this was removed.

2024-06-17 09:41 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +import {DssLitePsmInit, DssLitePsmInitConfig} from "../DssLitePsmInit.sol";
Resolving as this was removed.

2024-06-17 09:41 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.sol
> +    uint256 internal constant RAY = 10 ** 27;
Resolving as this was removed.

2024-06-17 09:42 UTC, oldchili commented on script/dependencies/phase-3/DssLitePsmMigrationPhase3.sol
> +import {DssLitePsmInstance} from "../DssLitePsmInstance.sol";
Resolving as this was removed.

2024-06-17 09:42 UTC, oldchili commented on script/dependencies/phase-3/DssLitePsmMigrationPhase3.sol
> +import {DssLitePsmInit, DssLitePsmInitConfig} from "../DssLitePsmInit.sol";
Resolving as this was removed.

2024-06-17 11:35 UTC, oldchili commented on script/dependencies/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +    function exec(bytes32) external;
Resolving as it was removed.

2024-06-17 11:54 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +        mig1Cfg = DssLitePsmMigrationConfigPhase1({
Resolving as this is handled.

2024-06-17 11:55 UTC, oldchili commented on script/dependencies/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +            srcTout: 0.01 ether,
Resolving as this is done.

2024-06-17 12:22 UTC, oldchili commented on script/dependencies/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +        mig1Cfg = DssLitePsmMigrationConfigPhase1({
resolving as handled

2024-06-17 12:24 UTC, oldchili commented on script/dependencies/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +            dstTout: 0.03 ether,
resolving as handled

2024-06-18 11:47 UTC, oldchili commented on src/deployment/DssLitePsmInit.sol
> +        require(uint256(PipLike(cfg.pip).read()) == 1 * WAD, "DssLitePsmInit/invalid-pip-val");
can we move this to be along with the other requires?

2024-06-18 11:47 UTC, oldchili commented on src/deployment/DssLitePsmMigration.sol
> +        uint256 mink = _min(src.ink, move);
@oddaf  is right, _subcap(src.ink, cfg.srcKeep) <= src.ink

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.sol
> +    uint256 dstTout; // [wad] - 10**18 = 100%
What is the rationale to have `dstTin` and `dstTout` and not have the same for `srcTin` and `srcTout`?. As all of them are kept as 0 so not sure why one of them is chosen to exist and the other not.
Maybe just remove `dstTin` and `dstTout`?

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +    uint256 srcKeep;
Nit - if `dstWant` is the last of the dst params,  then `srcKeep` should probably be the last of the src params.
Same for the other phase files.

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +         * community could replenish `srcPsm` and try to cast the spell again right the way so it does not fail.
the way => away

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +        autoLine.setIlk(res.srcIlk, cfg.srcMaxLine, cfg.srcGap, cfg.srcTtl);
Missing the "Notice: Setting auto-line parameters automatically resets time intervals..." as in phase 1.

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +        DssPsmLike(res.srcPsm).file("tin", cfg.srcTin);
We wanted a require that this is > 0, as otherwise anyone can avoid migrating anything - flash loan, take out the gem except srcKeep, execute the spell, then return the gem to the src psm.

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +        DssPsmLike(res.srcPsm).file("tout", cfg.srcTout);
We wanted a require that this is > 0, as otherwise anyone can easily migrate everything after the migration (using a flash-loan).

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.sol
> +    uint256 internal constant RAY = 10 ** 27;
still unused.

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.sol
> +            dss, MigrationConfig({srcPsmKey: cfg.srcPsmKey, dstPsmKey: cfg.dstPsmKey, srcKeep: 0, dstWant: srcInk})
Can probably avoid querying the `srcInk` and just using `dstWant: type(uint256).max`.

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.sol
> +        dss.vat.file(res.srcIlk, "line", 0);
General `Line` is not being taken care here. As there wouldn't be any remaining debt it should be safe to deduct the prev local line from it.

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.sol
> +        autoLine.setIlk(res.dstIlk, cfg.dstMaxLine, cfg.dstGap, cfg.dstTtl);
Missing the "Notice: Setting auto-line parameters automatically resets time intervals..." as in phase 1.

2024-06-18 11:47 UTC, oldchili commented on src/DssLitePsm.t.integration.sol
> +    function testTollMethods_Fuzz(address sender) public {
We don't usually use fuzzing for this kind of authirzation test.
Was there a specific reason for this change?

2024-06-18 11:47 UTC, oldchili commented on src/deployment/DssLitePsmInit.t.integration.sol
> +            (uint256 pink, uint256 part) = dss.vat.urns(ILK, inst.litePsm);
Probably if we want to do a sanity check, we should also be checking `rate == 0` (no prev vat.init) and `jug.ilks(ilk).duty == 0` (no prev jug.init).
We should also be checking the post, so we can prove that `vat.init` and `jug.init` executed.

2024-06-18 11:47 UTC, oldchili commented on src/deployment/DssLitePsmInit.t.integration.sol
> +        assertEq(litePsm.bud(address(pauseProxy)), 1, "after: `mom` not ward of `litePsm`");
ward => bud

2024-06-18 11:47 UTC, oldchili commented on src/deployment/DssLitePsmInit.t.integration.sol
> +
Missing checks for spotter `pip` and `mat` and verify that a `spot == RAY` in the vat was filled in.

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +interface EsmLike {
unused

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +    EsmLike esm;
unused

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +        esm = EsmLike(dss.chainlog.getAddress("MCD_ESM"));
unused

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +            dstWant: 10_000_000 * WAD,
Just a general reminder to align to the new values.

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +            srcKeep: 0 * WAD,
Consider keeping the same amount as required in phase 2 (e.g 100M).

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +            assertEq(srcArt, psrcArt - migCfg.dstWant, "after: src ink is not decreased by want");
ink => art

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +        assertEq(_amtToWad(gem.balanceOf(address(pocket))), migCfg.dstWant, "after: invalid gem balance for dst pocket");
We might also want to check how much decreased the gem in the gemJoin.

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +import {DssLitePsmMigration} from "../DssLitePsmMigration.sol";
still unused

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +            srcKeep: 0 * WAD,
same here, consider leaving 100M.

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +        this._checkMigrationPhase2();
Do we need to use "this." here?
We don't do it for the next test for example.

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +            assertGe(srcInk, mig2Cfg.srcKeep, "after: src ink is lower than src keep");
For the case where `dstWant` is limited because of `srcKeep` we probably want to check this as an equality.
Do we do this anywhere?

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +import {DssLitePsmMigration} from "../DssLitePsmMigration.sol";
still unused

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +            srcKeep: 0 * WAD,
same here

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +            assertGe(dstArt, pdstArt, "after: dst art is not increased at least by the moved amount");
Shouldn't this minimally add up the psrcInk/expectedMoveWad?

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +    function _wadToAmt(uint256 amt) internal view returns (uint256) {
amt => wad

2024-06-18 11:47 UTC, oldchili commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +        return amt / dstPsm.to18ConversionFactor();
amt => wad

2024-06-18 11:47 UTC, oldchili commented on script/input/5/README.md
can we remove the goerli files?

2024-06-18 12:28 UTC, amusingaxl commented on src/deployment/DssLitePsmMigration.sol
> +        uint256 mink = _min(src.ink, move);
Yeah, I realize that now. Thanks.

2024-06-18 12:50 UTC, amusingaxl commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.sol
> +    uint256 internal constant RAY = 10 ** 27;
🤦🏻‍♂️

2024-06-18 16:27 UTC, amusingaxl commented on src/DssLitePsm.t.integration.sol
> +    function testTollMethods_Fuzz(address sender) public {
This test was failing at some point during the refactor.

The reason was that `checkModifier` fills all parameters with zeros, so `usr` was being set to `address(0)`, which can make `transfer` and `transferFrom` fail in some implementations.

I didn't spend that much time investigating, I just assumed USDC implementation had changed or `address(0)` had been blacklisted somehow.

However, the original test seems to be working again, so I'm gonna revert the changes.

2024-06-18 16:51 UTC, amusingaxl commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +        this._checkMigrationPhase2();
Nope. `this.` is meant for tests that are expecting the spell to fail.

2024-06-18 16:54 UTC, amusingaxl commented on script/input/5/README.md
It's actually being removed. Can you please double-check?

2024-06-18 16:55 UTC, amusingaxl commented on script/input/5/README.md
I don't think we need them anymore, since Goerli is no longer operational.

2024-06-18 20:24 UTC, amusingaxl commented on src/deployment/DssLitePsmInit.t.integration.sol
> +
Added.

2024-06-18 20:24 UTC, amusingaxl commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +            dstWant: 10_000_000 * WAD,
Done.

2024-06-18 20:34 UTC, amusingaxl commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +        DssPsmLike(res.srcPsm).file("tout", cfg.srcTout);
Added to the beginning of the function.

2024-06-18 20:47 UTC, amusingaxl commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +            assertGe(srcInk, mig2Cfg.srcKeep, "after: src ink is lower than src keep");
Added a test case for this scenario with the relevant assertion tightened.

2024-06-18 20:48 UTC, amusingaxl commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.sol
> +        dss.vat.file(res.srcIlk, "line", 0);
Done.

2024-06-18 20:48 UTC, amusingaxl commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.sol
> +        autoLine.setIlk(res.dstIlk, cfg.dstMaxLine, cfg.dstGap, cfg.dstTtl);
Done.

2024-06-18 20:48 UTC, amusingaxl commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +        DssPsmLike(res.srcPsm).file("tin", cfg.srcTin);
Added to the beginning of the function.

2024-06-18 20:49 UTC, amusingaxl commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +        assertEq(_amtToWad(gem.balanceOf(address(pocket))), migCfg.dstWant, "after: invalid gem balance for dst pocket");
Done.

2024-06-18 20:51 UTC, amusingaxl commented on src/deployment/DssLitePsmInit.sol
> +}
Done.

2024-06-18 20:51 UTC, amusingaxl commented on src/deployment/DssLitePsmInit.sol
> +    function approve(address, uint256) external;
Done

2024-06-18 20:51 UTC, amusingaxl commented on src/deployment/DssLitePsmMigration.sol
> +    function symbol() external view returns (string memory);
Done

2024-06-18 20:52 UTC, amusingaxl commented on src/deployment/DssLitePsmMigration.sol
> +        uint256 mink = _min(src.ink, move);
Fixed

2024-06-18 20:52 UTC, amusingaxl commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.sol
> +}
Done

2024-06-18 20:52 UTC, amusingaxl commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +import {DssLitePsmInstance} from "../DssLitePsmInstance.sol";
Done.

2024-06-18 20:52 UTC, amusingaxl commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +}
Done

2024-06-18 20:52 UTC, amusingaxl commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.sol
> +import {DssLitePsmInit, DssLitePsmInitConfig} from "../DssLitePsmInit.sol";
Done

2024-06-18 20:52 UTC, amusingaxl commented on src/deployment/DssLitePsmInit.sol
> +        require(uint256(PipLike(cfg.pip).read()) == 1 * WAD, "DssLitePsmInit/invalid-pip-val");
Done

2024-06-18 20:52 UTC, amusingaxl commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +    uint256 srcKeep;
Done

2024-06-18 20:53 UTC, amusingaxl commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +         * community could replenish `srcPsm` and try to cast the spell again right the way so it does not fail.
TIL.
Done.

2024-06-18 20:53 UTC, amusingaxl commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +        autoLine.setIlk(res.srcIlk, cfg.srcMaxLine, cfg.srcGap, cfg.srcTtl);
Done.

2024-06-18 20:55 UTC, amusingaxl commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.sol
> +    uint256 internal constant RAY = 10 ** 27;
Fixed

2024-06-18 20:55 UTC, amusingaxl commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.sol
> +            dss, MigrationConfig({srcPsmKey: cfg.srcPsmKey, dstPsmKey: cfg.dstPsmKey, srcKeep: 0, dstWant: srcInk})
Done

2024-06-18 20:55 UTC, amusingaxl commented on src/DssLitePsm.t.integration.sol
> +    function testTollMethods_Fuzz(address sender) public {
Done

2024-06-18 20:56 UTC, amusingaxl commented on src/deployment/DssLitePsmInit.t.integration.sol
> +            (uint256 pink, uint256 part) = dss.vat.urns(ILK, inst.litePsm);
Done

2024-06-18 20:56 UTC, amusingaxl commented on src/deployment/DssLitePsmInit.t.integration.sol
> +        assertEq(litePsm.bud(address(pauseProxy)), 1, "after: `mom` not ward of `litePsm`");
Done

2024-06-18 20:56 UTC, amusingaxl commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +interface EsmLike {
Removed

2024-06-18 20:56 UTC, amusingaxl commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +    EsmLike esm;
Removed

2024-06-18 20:56 UTC, amusingaxl commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +        esm = EsmLike(dss.chainlog.getAddress("MCD_ESM"));
Removed

2024-06-18 21:20 UTC, amusingaxl commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +            srcKeep: 0 * WAD,
Done.

2024-06-18 21:20 UTC, amusingaxl commented on src/deployment/phase-1/DssLitePsmMigrationPhase1.t.integration.sol
> +            assertEq(srcArt, psrcArt - migCfg.dstWant, "after: src ink is not decreased by want");
Done

2024-06-18 21:20 UTC, amusingaxl commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +import {DssLitePsmMigration} from "../DssLitePsmMigration.sol";
Removed

2024-06-18 21:20 UTC, amusingaxl commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +            srcKeep: 0 * WAD,
Done

2024-06-18 21:20 UTC, amusingaxl commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +        this._checkMigrationPhase2();
Fixed

2024-06-18 21:21 UTC, amusingaxl commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +import {DssLitePsmMigration} from "../DssLitePsmMigration.sol";
Removed

2024-06-18 21:21 UTC, amusingaxl commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +            srcKeep: 0 * WAD,
Done

2024-06-18 21:21 UTC, amusingaxl commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +            assertGe(dstArt, pdstArt, "after: dst art is not increased at least by the moved amount");
Fixed

2024-06-18 21:21 UTC, amusingaxl commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +    function _wadToAmt(uint256 amt) internal view returns (uint256) {
Done

2024-06-18 21:21 UTC, amusingaxl commented on src/deployment/phase-3/DssLitePsmMigrationPhase3.t.integration.sol
> +        return amt / dstPsm.to18ConversionFactor();
Done

2024-06-19 09:03 UTC, oldchili commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +            assertGe(srcInk, mig2Cfg.srcKeep, "after: src ink is lower than src keep");
We should remove `Revert` from the test name.

Also, that test doesn't actually migrate anything right? (as there is exactly `srcKeep` beforehand).
That's a good case to check, but our intention was to test that a migration leaves exactly `srcKeep`.

2024-06-19 10:06 UTC, oldchili commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +
Thinking that as we now have an implicit assumption that the dst out fees are 0, we might want to add sanity checks for that (for all phases where some fees are assumed as 0).

2024-06-19 13:05 UTC, amusingaxl commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.sol
> +
Do the dst fees change anything regarding the migration strategy?
Since we're using the `NoFee` versions of the swapping functions, it surely does not affect the migration itself.
Am I missing something?

2024-06-19 13:11 UTC, amusingaxl commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +            assertGe(srcInk, mig2Cfg.srcKeep, "after: src ink is lower than src keep");
Ok, got it now.
Actually, I believe the assertion can be changed to `assertEq` now that we enforce `srcKeep`.

2024-06-19 13:19 UTC, amusingaxl commented on src/deployment/phase-2/DssLitePsmMigrationPhase2.t.integration.sol
> +            assertGe(srcInk, mig2Cfg.srcKeep, "after: src ink is lower than src keep");
Done.

2024-06-19 14:50 UTC, sunbreak1211 commented on src/DssLitePsm.t.integration.sol
> +    function testTollMethods_Fuzz(address sender) public {
The only explanation I can find for this to have failed in the past is that at some point the test address was kissed. But if working now, then let's move on.

2024-06-19 20:18 UTC, sunbreak1211 approved these changes
Looks good

2024-06-21 01:25 UTC, oddaf approved these changes

2024-06-21 13:03 UTC, merged