Adding phase 2 migration script
makerdao/dss-lite-psm pull request #18
Opened 2024-05-31 03:06 UTC by oddaf

2024-05-31 03:06 UTC, DaiFoundation-DevOps commented
[![CLA assistant check](https://cla.daifoundation.org/pull/badge/not_signed)](https://cla.daifoundation.org/makerdao/dss-lite-psm?pullRequest=18) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.daifoundation.org/makerdao/dss-lite-psm?pullRequest=18) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.daifoundation.org/check/makerdao/dss-lite-psm?pullRequest=18) it.</sub>

2024-05-31 15:03 UTC, 0xp3th1um approved these changes

2024-06-03 15:04 UTC, 0xdecr1pto approved these changes

2024-06-03 15:21 UTC, amusingaxl commented on script/dependencies/phase-2/DssLitePsmMigration.sol
> +    uint256 rump;
Nit: group related properties:
```suggestion
    bytes32 srcPsmKey;
    uint256 srcTin;
    uint256 srcTout;
    uint256 srcMaxLine;
    uint256 srcGap;
    uint256 srcTtl;
    bytes32 dstPsmKey;
    uint256 dstTin;
    uint256 dstTout;
    uint256 dstMaxLine;
    uint256 dstGap;
    uint256 dstTtl;
    uint256 buf;
    uint256 rump;
```

2024-06-03 16:05 UTC, amusingaxl requested changes

2024-06-03 16:05 UTC, amusingaxl commented on script/dependencies/phase-2/DssLitePsmMigration.sol
> +        dss.vat.grab(src.ilk, src.psm, address(this), address(this), -_int256(src.ink - cfg.rump), 0);
We probably want to keep `ink` and `art` balanced, otherwise the script on phase 3 [will fail](https://github.com/makerdao/dss-lite-psm/blob/5f80b52920336943ddec44d87298f1bddfe1349e/script/dependencies/phase-3/DssLitePsmMigration.sol#L134).

2024-06-03 16:05 UTC, amusingaxl commented on script/dependencies/phase-2/DssLitePsmMigration.sol
> +
Since we need to update `art` as well, we need to call `vat.heal()` after this step.

2024-06-03 17:18 UTC, oddaf commented on script/dependencies/phase-2/DssLitePsmMigration.sol
> +    uint256 rump;
done in [010e2a4](https://github.com/makerdao/dss-lite-psm/pull/18/commits/010e2a4bf6f6d8715ea039818f2fcd4a1a6f9c28)

2024-06-03 17:18 UTC, oddaf commented on script/dependencies/phase-2/DssLitePsmMigration.sol
> +        dss.vat.grab(src.ilk, src.psm, address(this), address(this), -_int256(src.ink - cfg.rump), 0);
done in [d47da6d](https://github.com/makerdao/dss-lite-psm/pull/18/commits/d47da6ddc555f9f1b4bb620064e6cbc3b83918fe)

2024-06-03 17:18 UTC, oddaf commented on script/dependencies/phase-2/DssLitePsmMigration.sol
> +
done in [d47da6d](https://github.com/makerdao/dss-lite-psm/pull/18/commits/d47da6ddc555f9f1b4bb620064e6cbc3b83918fe)

2024-06-03 18:24 UTC, amusingaxl approved these changes

2024-06-03 18:25 UTC, merged